### ISSUE TITLE
so.m.sm.cn not detected correctly

### ISSUE THREAD

**Issue by huang0808** [matomo-org/searchengine-and-social-list#48]
i add the search engine, it is no effect, the vistior log still show website:so.m.sm.cn. 
i do not kown why? who can tell me? thanks very much

**Comment by sgiehl** [comment]
Adding new search engines / social networks always only has effect to new visits. Old visits won't change.

**Comment by huang0808** [comment]
@sgiehl thanks your answer, but new visits still no change. Could you tell me why?  thanks

**Comment by sgiehl** [comment]
what exactly did you configure, and what is the exact referrer url that is not detected.
The ReferrersManager plugin should have the possibility to check referrer urls how they are detected...

**Comment by huang0808** [comment]
I configed the url exactly, you can see my upload image. thanks!
![sm](https://user-images.githubusercontent.com/34669327/40338106-e0a257f6-5da5-11e8-9a6e-c0c5c21ef657.png)

**Comment by sgiehl** [comment]
Seems like it would be detected correctly now. Nevertheless I'll add the host to our detections, so Matomo will be able to detect it without manual changes

**Comment by huang0808** [comment]
@sgiehl  still no work....
