### ISSUE TITLE
Bounce rate and Exit rate is higher than 100% in Entry pages of Actions. How do I fix it?

### ISSUE THREAD

**Issue by huang0808** [matomo-org/searchengine-and-social-list#49]
Bounce rate and Exit rate is higher than 100% in Entry pages and Exit pages of Actions. why show it?  who meet this issues? what methods to fix it? Thanks.

**Comment by sgiehl** [comment]
@huang0808  sorry this is not the right repository for this issue. Also it's a duplicate of https://github.com/matomo-org/matomo/issues/12808

**Comment by huang0808** [comment]
@sgiehl  okay,  thanks you tell me .
