### ISSUE TITLE
Plugin is not valid, it is missing the plugin.json file.

### ISSUE THREAD

**Issue by usa4646** [matomo-org/searchengine-and-social-list#81]
Plugin is not valid, it is missing the plugin.json file.

**Comment by sgiehl** [comment]
Hi @usa4646.
This repo is not a plugin. Its contents are included in Matomo, so there is no need to install it separately.

**Comment by usa4646** [comment]
Do you mean to upload directly to the directory, thank you

**Comment by sgiehl** [comment]
You do not need to do anything. Matomo includes it automatically and will also update it automatically.
