### ISSUE TITLE
Recognize Workplace as a Social Network source

### ISSUE THREAD

**Issue by Flameeyes** [matomo-org/searchengine-and-social-list#90]
(I would send a pull request, but the license [makes it harder](https://flameeyes.blog/2020/04/16/making-it-easy-to-contribute-code/).)

[Workplace](https://www.workplace.com/) is a business communication platform by Meta (full disclosure: my employer, although I do not work on this product). Links followed from Workplace use a very similar URL cloak as Facebook, using the hostnames `l.workplace.com` and `lm.workplace.com`.

**Comment by michalkleiner** [comment]
Thanks for opening the issue, @Flameeyes.

Does the licence _just_ make it harder for you (and you wanted to make that point), or makes it truly impossible and you are not allowed to open a PR on a project that uses CC0 licence?

**Comment by Flameeyes** [comment]
I wouldn't say that it is not possible in any circumstance for me to open a PR for a CC0-licensed repo (like it practically is for AGPL3), but it does raise the bar for doing so quite significantly, unfortunately. It's mostly by way of an apology for not just sending a PR for what is effectively such a minor change that me describing and you reading take more time than the change itself 😅
