### ISSUE TITLE
Yandex funnel coming from `ya.ru`

### ISSUE THREAD

**Issue by Flameeyes** [matomo-org/searchengine-and-social-list#91]
(I would send a pull request, but the license [makes it harder](https://flameeyes.blog/2020/04/16/making-it-easy-to-contribute-code/).)

It appears `ya.ru` is a new hostname used in URL cloaking coming from Yandex. It does not appear to include the keywords, at least from the logs I have.

**Comment by sgiehl** [comment]
@Flameeyes I've created a PR to fix this. Let me know if that looks fine for you.
